{
  "contest": 302,
  "handle": "Im_th3AK",
  "risk": "2",
  "title": "Calls inside a loop might lead to a denial-of-service attack.",
  "issueId": 1855,
  "issueUrl": "https://github.com/code-423n4/2023-10-nextgen-findings/issues/1855"
}